[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mi_crypto_lib"
version = "1.0.10"
description = "Biblioteca de criptografia para el proyecto 1"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Raul"}
]

[tool.setuptools.packages.find]
include = ["mi_crypto_lib*"]
